export interface Product {
  id: string;
  imageUrl: string;
  title: string;
  description: string;
  price: string;
  otherPrice?: string;
  type: "DISCOUNTED" | "NEW" | "NORMAL";
  typeValue?: string;
}

export const PRODUCTS = [
  {
    id: "10",
    imageUrl: "/watch1.png",
    title: "Tissot T100.417.11.051.01 PRS 516 Metal Band Men Watch",
    description: "Mechanism: Analog(Quartz) Feature: Date/Chronograph Dial Color: Black Dial Shape: Round",
    price: "5700",
    otherPrice: "3.500.000",
    type: "DISCOUNTED",
    typeValue: "-30%",
  },
  {
    id: "20",
    imageUrl: "/watch2.png",
    title: "Tissot T114.417.11.037.00 PRC 200 Chronograph Metal Band Men Watch",
    description: "Mechanism: Analog(Quartz) Feature: Chronograph Dial Color: White Dial Shape: Round Dial Size approx: 41mm",
    price: "3000",
    otherPrice: "3.500.000",
    type: "DISCOUNTED",
    typeValue: "-30%",
  },
  {
    id: "30",
    imageUrl: "/watch3.png",
    title: "CURREN Original Brand Stainless Steel Band Wrist Watch For Men With Brand (Box & Bag)-8466",
    description: "Dial Diameter: 43mm Case Thickness: 12mm Watch Length: 240mm Band Width: 20mm Watch Weight: 115g",
    price: "5000",
    otherPrice: "14.000.000",
    type: "DISCOUNTED",
    typeValue: "-50%",
  },
  {
    id: "40",
    imageUrl: "/watch4.png",
    title: "CURREN Original Brand Stainless Steel Band Wrist Watch For Men With Brand (Box & Bag)-8023",
    description: "Band Material Type: Stainless Steel Band Width: 24mm Case Material: Alloy Case Shape: Round Case Thickness: 10mm",
    price: "7000",
    otherPrice: "8000",
    type: "NEW",
    typeValue: "New",
  },
  {
    id: "50",
    imageUrl: "/watch5.png",
    title: "Ferro FM11372A-D Metal Band Men Watch",
    description: "Feature: Multi-Function Dial Color: Silver Dial Shape: Round Dial Size approx: 39mm Glass: Hardlex Crystal Case Color: Silver",
    price: "6000",
    otherPrice: "",
    type: "NORMAL",
    typeValue: "",
  },

  {
    id: "60",
    imageUrl: "/watch6.png",
    title: "Ferro FM40102A-A Metal Band Men Watch",
    description: "Case Color: Silver Case width approx: 43mm Case Material: Super Metal Band Color: Silver Band Material: Stainless Steel Water Resistance: 30 Meter",
    price: "4990",
    otherPrice: "",
    type: "NEW",
    typeValue: "New",
  },
  {
    id: "70",
    imageUrl: "/watch7.png",
    title: "Ferro FM11248A-D2 Metal Band Men Watch",
    description: "Mechanism: Analog(Quartz) Feature: Chronograph Dial Color: Black Dial Shape: Round Dial Size approx: 43mm Glass: Hardlex Crystal Case Color: Silver",
    price: "5999",
    otherPrice: "14.000.000",
    type: "DISCOUNTED",
    typeValue: "-50%",
  },

  {
    id: "80",
    imageUrl: "/watch8.png",
    title: "Tissot T127.407.11.091.01 Gentleman Powermatic 80 Silicum Metal Band Men Watch",
    description: "Mechanism: Analog(Automatic) Feature: Date Dial Color: Green Dial Shape: Round Dial Size approx: 38mm Glass: Sapphire Crystal",
    price: "7000",
    otherPrice: "",
    type: "NEW",
    typeValue: "New",
  },
  {
    id: "90",
    imageUrl: "/watch9.png",
    title: "Tissot T120.417.11.041.01 Chronograph Driver Men Watch",
    description: "Dial Shape: Round Dial Size approx: 44mm Glass: Sapphire crystal Case Color: Silver Case width approx: 46mm",
    price: "7999",
    otherPrice: "3.500.000",
    type: "DISCOUNTED",
    typeValue: "-30%",
  },
  // {
  //   id: "100",
  //   imageUrl: "/images/p_2.png",
  //   title: "Leviosa V2",
  //   description: "Stylish cafe chair",
  //   price: "27000",
  //   otherPrice: "3.500.000",
  //   type: "DISCOUNTED",
  //   typeValue: "-30%",
  // },
  // {
  //   id: "110",
  //   imageUrl: "/images/p_3.png",
  //   title: "Lolito Vilo",
  //   description: "Luxury big sofa",
  //   price: "500",
  //   otherPrice: "14.000.000",
  //   type: "DISCOUNTED",
  //   typeValue: "-50%",
  // },
  // {
  //   id: "120",
  //   imageUrl: "/images/p_4.png",
  //   title: "Respira Uno",
  //   description: "Outdoor bar table and stool",
  //   price: "7000",
  //   otherPrice: "",
  //   type: "NEW",
  //   typeValue: "New",
  // },
  // {
  //   id: "130",
  //   imageUrl: "/images/p_5.png",
  //   title: "Grifo Yon",
  //   description: "Night lamp",
  //   price: "600",
  //   otherPrice: "",
  //   type: "NORMAL",
  //   typeValue: "",
  // },

  // {
  //   id: "140",
  //   imageUrl: "/images/p_6.png",
  //   title: "Muggo Sacpe",
  //   description: "Small mug",
  //   price: "4000",
  //   otherPrice: "",
  //   type: "NEW",
  //   typeValue: "New",
  // },
  // {
  //   id: "150",
  //   imageUrl: "/images/p_7.png",
  //   title: "Pingky Hoi",
  //   description: "Cute bed set",
  //   price: "500",
  //   otherPrice: "14.000.000",
  //   type: "DISCOUNTED",
  //   typeValue: "-50%",
  // },

  // {
  //   id: "160",
  //   imageUrl: "/images/p_8.png",
  //   title: "Potty Been",
  //   description: "Minimalist flower pot",
  //   price: "7000",
  //   otherPrice: "",
  //   type: "NEW",
  //   typeValue: "New",
  // },
];
